export const IPC = {
  masterOptions: 'master:options',
  subjectsList: 'subjects:list',
  subjectsSave: 'subjects:save',
  detailsList: 'details:list',
  detailsSave: 'details:save',
  assemblyOptions: 'assembly:options',
  assemblyList: 'assembly:list',
  assemblySave: 'assembly:save',
  assemblyItemFromDetail: 'assembly:itemFromDetail',
  assemblyMerge: 'assembly:merge',
  assemblyPromote: 'assembly:promote',
  estimateRowsList: 'estimateRows:list',
  estimateRowsSave: 'estimateRows:save',
  roomSheetGet: 'roomSheet:get',
  roomSheetSave: 'roomSheet:save',
  roomFittingRegister: 'roomSheet:fittingRegister',
  frameSheetGet: 'frameSheet:get',
  frameSheetSave: 'frameSheet:save',
  frameRoomsList: 'frameSheet:rooms',
  generalSheetGet: 'generalSheet:get',
  generalSheetSave: 'generalSheet:save',
  transferRowsList: 'transferRows:list',
  transferRowsSave: 'transferRows:save',
  aggregateRun: 'aggregate:run',
  aggregateGet: 'aggregate:get',
  aggregateRuns: 'aggregate:runs',
  deductionLimitGet: 'settings:deductionLimitGet',
  deductionLimitSave: 'settings:deductionLimitSave',
  fittingsList: 'fittings:list',
  fittingsSave: 'fittings:save',
  projectLedger: 'project:ledger',
  projectCreate: 'project:create',
  projectCopy: 'project:copy',
  projectSave: 'project:save',
  projectReorder: 'project:reorder',
  projectFieldsSave: 'project:fieldsSave',
  projectOpenWindow: 'project:openWindow',
  windowClose: 'window:close'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
