export const IPC = {
  masterOptions: "master:options",
  basicMastersList: "basicMasters:list",
  basicMasterSave: "basicMasters:save",
  subjectsList: "subjects:list",
  subjectsSave: "subjects:save",
  projectMastersCopy: "projectMasters:copy",
  projectMastersKinds: "projectMasters:kinds",
  detailsList: "details:list",
  detailsListInUse: "details:listInUse",
  detailsSave: "details:save",
  detailsSyncToBasic: "details:syncToBasic",
  detailsCopyFromBasic: "details:copyFromBasic",
  detailChangeLogsList: "details:changeLogs",
  assemblyOptions: "assembly:options",
  assemblyList: "assembly:list",
  assemblySave: "assembly:save",
  assemblyItemFromDetail: "assembly:itemFromDetail",
  assemblyMerge: "assembly:merge",
  assemblyPromote: "assembly:promote",
  estimateRowsList: "estimateRows:list",
  estimateRowsSave: "estimateRows:save",
  estimateRowsFilledSheets: "estimateRows:filledSheets",
  roomSheetGet: "roomSheet:get",
  roomSheetSave: "roomSheet:save",
  roomFittingRegister: "roomSheet:fittingRegister",
  frameSheetGet: "frameSheet:get",
  frameSheetSave: "frameSheet:save",
  frameRoomsList: "frameSheet:rooms",
  generalSheetGet: "generalSheet:get",
  generalSheetSave: "generalSheet:save",
  pitSheetGet: "pitSheet:get",
  pitSheetSave: "pitSheet:save",
  transferRowsList: "transferRows:list",
  transferRowsSave: "transferRows:save",
  aggregateRun: "aggregate:run",
  aggregateGet: "aggregate:get",
  aggregateRuns: "aggregate:runs",
  aggregateSaveEdits: "aggregate:save-edits",
  aggregateSetUnused: "aggregate:set-unused",
  estimateRowChecks: "estimate-rows:checks",
  formworkTransferGet: "formworkTransfer:get",
  formworkTransferSaveRules: "formworkTransfer:saveRules",
  formworkTransferRun: "formworkTransfer:run",
  breakdownGet: "breakdown:get",
  breakdownVersions: "breakdown:versions",
  breakdownTransfer: "breakdown:transfer",
  breakdownSaveRows: "breakdown:saveRows",
  breakdownSaveSettings: "breakdown:saveSettings",
  breakdownConfirm: "breakdown:confirm",
  breakdownDeleteVersion: "breakdown:deleteVersion",
  breakdownExport: "breakdown:export",
  deductionLimitGet: "settings:deductionLimitGet",
  deductionLimitSave: "settings:deductionLimitSave",
  fittingsList: "fittings:list",
  fittingsSave: "fittings:save",
  fittingPartValuesGet: "settings:fittingPartValuesGet",
  fittingPartValuesSave: "settings:fittingPartValuesSave",
  projectLedger: "project:ledger",
  projectCreate: "project:create",
  projectCopy: "project:copy",
  projectSave: "project:save",
  projectReorder: "project:reorder",
  projectFieldsSave: "project:fieldsSave",
  projectOpenWindow: "project:openWindow",
  /** 工事の内容が変わったことを開いているすべての画面へ知らせる（送信専用） */
  projectChanged: "project:changed",
  /** 明細入力を独立したウィンドウで開く */
  calcWindowOpen: "calc:openWindow",
  /** 元の画面 → 明細入力ウィンドウへ内容を渡す */
  calcWindowPush: "calc:push",
  /** 明細入力ウィンドウ → 元の画面へ入力を返す */
  calcWindowApply: "calc:apply",
  /** 明細入力ウィンドウの読み込み完了（最新の内容を要求する） */
  calcWindowReady: "calc:ready",
  /** 明細入力ウィンドウ側のイベント名（送信専用） */
  calcWindowState: "calc:state",
  calcWindowInput: "calc:input",
  calcWindowClosed: "calc:closed",
  backupInfo: "backup:info",
  backupCreate: "backup:create",
  backupRestore: "backup:restore",
  printPaper: "print:paper",
  printPdf: "print:pdf",
  screenExcel: "print:excel",
  windowClose: "window:close",
  windowFocus: "window:focus",
  imeMode: "ime:mode",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
